import {
  makeStyles,
  shorthands,
  tokens,
  Text,
  Tooltip,
} from "@fluentui/react-components";
import { Sparkle20Filled, Info16Regular } from "@fluentui/react-icons";
import React from "react";

const useStyles = makeStyles({
  summaryCard: {
    ...shorthands.border("1px", "solid", "#d8dcf5"),
    borderRadius: "12px",
    padding: "20px",
    marginBottom: "20px",
    backgroundColor: "#fafaff",
  },
  summaryHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "12px",
  },
  summaryIcon: {
    color: "#5b5fc7",
  },
  summaryBadge: {
    display: "inline-flex",
    fontSize: "10px",
    fontWeight: 600,
    padding: "2px 8px",
    borderRadius: "4px",
    backgroundColor: "#e8ebf9",
    color: "#5b5fc7",
  },
  insightGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "12px",
    marginTop: "16px",
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  insightItem: {
    display: "flex",
    gap: "10px",
    padding: "12px",
    borderRadius: "8px",
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
  },
  insightIcon: {
    flexShrink: 0,
    marginTop: "2px",
  },
});

interface AISummaryCardProps {
  title?: string;
  children: React.ReactNode;
  insights?: React.ReactNode;
  showDisclaimer?: boolean;
}

/**
 * Reusable AI Summary Card component with consistent LogIQ branding
 * 
 * @param title - Custom title for the AI summary (defaults to "LogIQ™ AI Insights")
 * @param children - Main summary content/text
 * @param insights - Optional insight grid items
 * @param showDisclaimer - Whether to show AI disclaimer tooltip (default: true)
 */
export const AISummaryCard: React.FC<AISummaryCardProps> = ({
  title = "LogIQ™ AI Insights",
  children,
  insights,
  showDisclaimer = true,
}) => {
  const styles = useStyles();

  return (
    <div className={styles.summaryCard}>
      <div className={styles.summaryHeader}>
        <Sparkle20Filled className={styles.summaryIcon} />
        <Text weight="bold" size={500}>{title}</Text>
        <span className={styles.summaryBadge}>AI Summary</span>
        {showDisclaimer && (
          <Tooltip
            content={
              <div style={{ maxWidth: "300px" }}>
                <Text size={200} weight="semibold" style={{ display: "block", marginBottom: "4px" }}>
                  AI-Generated Content
                </Text>
                <Text size={200}>
                  All insights and recommendations are generated by AI and should be reviewed by qualified professionals.
                  LogIQ is not responsible for any issues, inaccuracies, or hallucinations in AI-generated content.
                </Text>
              </div>
            }
            relationship="description"
          >
            <Info16Regular
              style={{
                marginLeft: "auto",
                color: tokens.colorNeutralForeground3,
                cursor: "pointer",
              }}
            />
          </Tooltip>
        )}
      </div>
      
      <Text size={300} style={{ color: tokens.colorNeutralForeground2, lineHeight: "1.6" }}>
        {children}
      </Text>

      {insights && (
        <div className={styles.insightGrid}>
          {insights}
        </div>
      )}
    </div>
  );
};

interface InsightItemProps {
  icon: React.ReactNode;
  title: string;
  description: string;
}

/**
 * Individual insight item for use within AISummaryCard
 */
export const InsightItem: React.FC<InsightItemProps> = ({ icon, title, description }) => {
  const styles = useStyles();

  return (
    <div className={styles.insightItem}>
      <div className={styles.insightIcon}>{icon}</div>
      <div>
        <Text weight="semibold" size={300}>{title}</Text>
        <Text size={200} style={{ color: tokens.colorNeutralForeground3, display: "block", marginTop: "2px" }}>
          {description}
        </Text>
      </div>
    </div>
  );
};
